### ISSUE TITLE
super() in initialize throws error

### ISSUE THREAD

**Issue by lramamoo** [state-machines/state_machines-activerecord#63]
Hi,
using ruby-2.2.2, rails 4.1.16. 

When i try to call super() in the initialize method i am getting the following error:

ArgumentError:
       wrong number of arguments (1 for 0)

Below is the code:

```
class DefaultWorkflow
  include ActiveModel::Dirty
  include ActiveModel::Validations
  attr_accessor :state, :workflow_type, :workflow_name, :ticket
  define_attribute_methods [:state]

  def initialize(state = nil, ticket = nil)
    @ticket = ticket
    super()
  end

   state_machine :initial => :open do

    event :start_progress do
      transition [:open, :rework] => :in_progress
    end
  end
end
```

**Comment by rafaelfranca** [comment]
This is because super is expecting one argument and you are not passing any.

**Comment by lramamoo** [comment]
```
ArgumentError: wrong number of arguments (1 for 0)
	from /Users/lavanya/rails/service_desk/vendor/bundle/ruby/2.2.0/gems/state_machines-activemodel-0.5.0/lib/state_machines/integrations/active_model.rb:408:in `initialize'
	from /Users/lavanya/rails/service_desk/vendor/bundle/ruby/2.2.0/gems/state_machines-activemodel-0.5.0/lib/state_machines/integrations/active_model.rb:408:in `block in initialize'
	from /Users/lavanya/rails/service_desk/vendor/bundle/ruby/2.2.0/gems/state_machines-0.5.0/lib/state_machines/machine_collection.rb:26:in `initialize_states'
	from /Users/lavanya/rails/service_desk/vendor/bundle/ruby/2.2.0/gems/state_machines-activemodel-0.5.0/lib/state_machines/integrations/active_model.rb:408:in `initialize'
	from /Users/lavanya/rails/service_desk/app/models/workflow.rb:27:in `initialize'
	from (irb):1:in `new'
	from (irb):1
	from /Users/lavanya/rails/service_desk/vendor/bundle/ruby/2.2.0/gems/railties-4.1.16/lib/rails/commands/console.rb:90:in `start'
	from /Users/lavanya/rails/service_desk/vendor/bundle/ruby/2.2.0/gems/railties-4.1.16/lib/rails/commands/console.rb:9:in `start'
	from /Users/lavanya/rails/service_desk/vendor/bundle/ruby/2.2.0/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/lavanya/rails/service_desk/vendor/bundle/ruby/2.2.0/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/lavanya/rails/service_desk/vendor/bundle/ruby/2.2.0/gems/railties-4.1.16/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by rafaelfranca** [comment]
What is the inheritance chain of your object? It seems you have one module that has an initialize without arguments.
