### ISSUE TITLE
defining associations in state block break

### ISSUE THREAD

**Issue by HoneyryderChuck** [state-machines/state_machines-activerecord#77]
I want a relation to only be available to the model when in a certain state:

```ruby
state_machine :initial do
  state :finished do
    has_many :clubs
  end
...
```

This doesn't work however, with the following error: 

```
ArgumentError:
  Unknown key: :if. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table, :foreign_type, :index_errors
# /usr/local/bundle/gems/state_machines-0.4.0/lib/state_machines/assertions.rb:18:in `block in assert_valid_keys'
# /usr/local/bundle/gems/state_machines-0.4.0/lib/state_machines/assertions.rb:16:in `each_key'
# /usr/local/bundle/gems/state_machines-0.4.0/lib/state_machines/assertions.rb:16:in `assert_valid_keys'
# /usr/local/bundle/gems/activerecord-5.0.7.1/lib/active_record/associations/builder/association.rb:78:in `validate_options'
# /usr/local/bundle/gems/activerecord-5.0.7.1/lib/active_record/associations/builder/association.rb:44:in `create_reflection'
# /usr/local/bundle/gems/activerecord-5.0.7.1/lib/active_record/associations/builder/association.rb:29:in `build'
# /usr/local/bundle/gems/activerecord-5.0.7.1/lib/active_record/associations.rb:1371:in `has_many'
# /usr/local/bundle/gems/state_machines-0.4.0/lib/state_machines/state_context.rb:130:in `method_missing'
# ./app/models/owner/base.rb:26:in `block (2 levels) in <class:Base>
...
```

The `if` error, however, doesn't come from my code, as shown above, but from the state_machine code, which introduces an `if` condition before calling rails's `has_many`. 

I'm using rails 5.0, btw.

**Comment by seuros** [comment]
Why do you want to remove the relation definition ? 
ActiveRecord relations are meant to reflect the database relations. They will return an empty ActiveRecord::Associations::CollectionProxy if the query return nothing.

**Comment by HoneyryderChuck** [comment]
The why is not important IMO. Shouldn't this be possible?

**Comment by seuros** [comment]
It not possible unless Activerecord support conditional relationship.
